language: julia

os:
  - osx
  - linux

julia:
  - 0.4
  - 0.5
  - nightly

notifications:
  email: true

before_install:
  - pip show matplotlib || pip install --user matplotlib

script:
  - julia -e 'Pkg.init(); Pkg.clone("EasyPhys")'
  - julia -e 'Pkg.test("EasyPhys")'

cache: pip

matrix:
  allow_failures:
    - os: linux
