language: julia

os:
  - osx
  - linux

julia:
  - 0.5
  - nightly

notifications:
  email: false

script:
  # need to get LsqFit from master, for some reason
  - julia -e 'Pkg.init(); Pkg.clone("https://github.com/JuliaOpt/LsqFit.jl.git"); Pkg.clone(pwd()); Pkg.update()'
  - julia -e 'ENV["PYTHON"]=""; Pkg.build("PyCall"); using PyPlot; Pkg.test("EasyPhys", coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("EasyPhys")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

matrix:
  allow_failures:
    - julia: nightly
