language: julia

os:
  - osx
  - linux

julia:
  - 0.4
  - 0.5
  - nightly

notifications:
  email: true

before_install:
  - pip install --upgrade pip
  - pip install --user matplotlib

matrix:
  allow_failures:
    - os: linux
  include:
    - os: linux
      sudo: required
