language: julia

os:
  - osx
  - linux

julia:
  - 0.5
  - nightly

notifications:
  email: false

script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.update()'
  - julia -e 'ENV["PYTHON"]=""; Pkg.build("PyCall"); using PyPlot; Pkg.test("EasyPhys", coverage=true)'

matrix:
  allow_failures:
    - julia: nightly
