language: julia

os:
  - osx
  - linux

julia:
  - 0.5
  - nightly

notifications:
  email: false

script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.update()'
  - julia -e 'Pkg.test("EasyPhys")'

matrix:
  allow_failures:
    - julia: nightly
