language: julia

os:
  - osx
  # - linux

julia:
  # - 0.4
  - 0.5
  # - nightly

notifications:
  email: false

before_install:
  - pip show matplotlib || pip install --user matplotlib

script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd())'
  - julia -e 'Pkg.test("EasyPhys")'

cache: pip

# matrix:
#   allow_failures:
#     - os: linux
#     - julia: nightly
