language: julia

os:
  - osx
  - linux

julia:
  - 0.4
  - 0.5
  - nightly

notifications:
  email: false

script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd())'
  - julia -e 'ENV["PYTHON"]=""; Pkg.build("PyCall"); Pkg.test("EasyPhys")'

matrix:
  allow_failures:
    - os: linux
    - julia: nightly
